name: google-chat-notification

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches: [ master ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "notify"
  notify:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      -  uses: Co-qn/google-chat-notification@v1
         with:
           # job name.
           name: PR
           # google chat webhook url.
           url: https://chat.googleapis.com/v1/spaces/AAAAra-BjYE/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=6kZEXnYj9msuEt7wCQU6ChsY3WQAk-isjdzMoLxH9gY%3D
           # job status.
           status: ${{ job.status }}

